### ISSUE TITLE
Obsolete Functions

### ISSUE THREAD

**Issue by AgLaApps** [walkinside/sdk#14]
Good morning,

I´m working right now updating some of our plugins to COMOS Walkinside 10.2 version and I found that the functions Load and Unload are obsolete, so I would like to know the how to modify this code to use the properly SDK functions:

`string currentElementPath = dllFullPath + current.Item1.Text.ToString() + ".dll";
 IVRViewerSdk pviewer;
 pviewer.PluginManager.Load(currentElementPath);
 pviewer.PluginManager.Unload(currentElementPath);`

Looking forward to any response.
Thanks.

**Comment by kveretennicov** [comment]
@aglaapps, sounds like you have an interesting use case (and an unexpected one, to be honest).

Can you describe what you have implemented using `IVRPluginManager.Load/Unload`? Do you have Walkinside Viewer plug-ins that depend on your other plug-ins, so they must be loaded/unloaded together?

Once we understand your use case in detail, we can think of a way to address this need. It may be some new API in a future release or even reverting deprecation of `Load/Unload`; there can also be a way to change your plug-in design so that `Load/Unload` is not needed.

**Comment by AgLaApps** [comment]
Basically we have a master plugin that manage all our other plugins.
When we activate the Master Plugin in the Options/Settings/Plugins a list of ToolStripMenuItem with a EventHandler is created as follows:
`public bool CreatePlugin(IVRViewerSdk pars)`
`{`
`List<Tuple<ToolStripMenuItem, dllTypes>> menuItemsList;`
`menuItemsList.Add(new Tuple<ToolStripMenuItem, dllTypes>(pwi_item.DropDownItems.Add(current) as ToolStripMenuItem, dllTypes.Full));`
`menuItemsList.Last().Item1.Click += new EventHandler(MenuClick);`
`}`
When we click in an element of the menu the function `void MenuClick(object sender, EventArgs e)` is called and we go through the list of plugins, the element is checked in the menu `current.Item1.Checked = true;` and the selected plugin is loaded with `pviewer.PluginManager.Load(dllpath);`.
If we close the project or deactivate the plugin we go through all the elements unloading them with `pviewer.PluginManager.Unload(dllpath);`

If you need more information I will provide it as soon as possible.

**Comment by kveretennicov** [comment]
Thank you, the picture is getting clearer.

As I understand, you have a sort of plug-in hierarchy, with one Master Walkinside plug-in and a few Secondary plug-ins. Secondary plug-ins are also implemented as full-fledged Walkinside plug-ins.

A few questions to better understand the design, especially the reason for Secondary plug-ins to be Walkinside plug-ins and not just classes inside Master assembly or inside their own plain .NET assemblies:
1. Do you distribute Secondary plug-ins on their own, without Master? (my guess is no)
2. Do you distribute different sets of Secondary plug-ins depending on customer? (my guess is yes)
3. Do secondary plug-ins communicate with each other? If yes, how do you do it?
4. Does it make sense that user can enable and disable Secondary plug-ins via Walkinside's Settings dialog and thus bypass your Master menu? (my guess is no)
5. Are there some other advantages of having Secondary plug-ins as independent Walkinside plug-ins?

With this information we should be able to discuss the matter with other @walkinside/devs and come up with a recommendation after holiday season is over. For now you don't have to worry too much, because according to our [Compatibility Policy](https://walkinside.github.io/sdk/docs/html/policy.html) these deprecated APIs will stay around at least until 10.3, which normally is not expected before 2018.

**Comment by AgLaApps** [comment]
Thank you for the fast reply,

First of all I want to clarify that the design is not my own :) I'm only just upgrading the plugins from Walkinside 7 to 10.2 improving some functionalities but maintaining the main design of Master and Secondary plug-ins.

1. As you guessted the Secondary plug-ins need to be distributed with the Master.
2. The Secondary plug-ins could be full functional or with limited capabilities.
3. Right now the plug-ins don't communicate with each other, but if you tell me how that could be achieved some of the future plugins could incorporate that capability.
4. The user enable and disable the plug-ins only through Master menu.
5. The Master Plugin shows automatically the Secondary plug-ins of the owner, so the user only need to click to enable the one that you want to use without needing to go to the Options / Settings / Plugins to enable the plugin and then go to other menu and activate it.

Right now despite the message of deprecated functions the plugins works fine but if there is an easy way to change the functions to the up to date version I would like to do it.

**Comment by kveretennicov** [comment]
@aglaapps, we've just had an internal discussion about this issue. The conclusion is that the deprecation stays and that we will not plan any alternative APIs to allow one plug-in to load/unload other plug-ins.

Here is what we advise for your situation.

For the short term, as mentioned, you can just keep using these deprecated APIs. They are not going away tomorrow.

For the longer term it would be best to combine your Master and Secondary plug-ins into a single plug-in. That way you can fully control which parts of AgLa Apps to activate/deactivate and when. Users or other plug-ins will not be able to "break" your load/unload logic via `Settings | Plugins` GUI or via `Load/Unload` API. It will also make it easier for Secondaries to communicate, if needed.

One possible mid-term solution could be to keep Master and Secondary in separate assemblies, like now, but modify all Secondary plug-ins so that Walkinside does not recognize them as plug-ins. Then you will need to implement a bit of Walkinside's plug-in loading magic by yourself: load Secondary assemblies, initialize and deinitialize them, keep track which Secondaries should be loaded at startup, etc. It may turn out a bit more complicated than it seems, so it may be actually easier for you to go for the single plug-in approach.

Does that make sense to you?

CC @walkinside/devs @walkinside/staff

**Comment by kveretennicov** [comment]
In case you have more questions, feel free to reopen this issue or open another one.
