### ISSUE TITLE
How to set FadeValues to customized label, also how to modify Redlining Fadevalues

### ISSUE THREAD

**Issue by makiko-SYSPRO** [walkinside/sdk#19]
Hello - please let me know if anyone can answer my questions , , , 
I used WIV7 SDK to capture screen shot, but it need to be upgrade to V10.2SP1.
So I would like to know the information by V10.2SP1 envrionment.

1) By modifying Viewer Example 7, I could add own label into 3D model. Now , I want to add Fadevalue options like Redlining. How should I modify the code ?

2) Is there anyway to modify initial Redlining Fadevalue by SDK ? 

![label_customization](https://cloud.githubusercontent.com/assets/25055031/21982169/674528a6-dc2e-11e6-879b-4291c0d3e4f9.png)

* I tried to uploaded source files by ZIP, but the system didn't recognize my .zip file.
  I saved WIPlugin.cs as .txt, you can check the source code in it. Hope it is help you to understand what I am  asking . . . 
  
[WIPlugin.cs.txt](https://github.com/walkinside/sdk/files/708256/WIPlugin.cs.txt)

**Comment by kveretennicov** [comment]
@makiko-syspro, thanks for your request, we are always glad to hear back from users of our SDK.

If I understand correctly, you use `IVRLabelGroup` and  `IVRLabel`. Have you already tried `IVRLabelGroup.MinimumDistance` and `IVRLabelGroup.MaximumDistance` properties? Normally they work the same way as fade distances on redlines.

**Comment by kveretennicov** [comment]
You can make the following small change to [`MainForm.cs` of Example 7](https://github.com/walkinside/sdk/blob/30cd44240450edb6b7c7ee3d1753bcebb02c5d14/examples/official/Viewer%20SDK/Ex7.Labels/MainForm.cs#L31) to set fade distance:

```c#
m_LabelGroup = SDKViewer.CreateLabelGroup("Example7");
m_LabelGroup.MaximumDistance = 3; // <- add this to have fade distance 3. 
```

Let us know if this works for you.

**Comment by makiko-SYSPRO** [comment]
Hello kveretennicov,

Thank you for your reply. Yes, it worked for own label I created by SDK program.
What about "Redlining" group default distance ? WI set difault distance as 10, but can we change it to
other number by SDK ?

**Comment by gcorvala** [comment]
Hello,

For redlines created with the existing "Redlining" view, there is currently no way to modify default values like fading distances.

A solution would be to implement your own view, where each IVRRedlineGroup would have your desired setup.
That way, you can follow the suggestion from @kveretennicov in order to setup each group properly:

  var redlineGroup = redlineManager.CreateGroup("a redline group name");
  redlineGroup.FadeMinimumDistance = 0;
  redlineGroup.FadeMaximumDistance = 3;

Then each redline created within this group will have the fade maximum distance set to 3 meters.

  var newRedline = redlineGroup.Items.Add("a redline name", new VRVector3D(1.0, 2.0, 3.0);

If this solution does not fit your needs, could you please share with us how your are planning to use these redlines.

**Comment by kveretennicov** [comment]
Closing for the time being.
Feel free to re-open if you need more assistance from us. Thank you.

**Comment by dkOogway** [comment]
Hello,
Is labelgroup is store as text file or in which format & where is saved?

--
Kind regards
