### ISSUE TITLE
How to open Plugin window automatically on Walkinside start

### ISSUE THREAD

**Issue by kkneip** [walkinside/sdk#25]
When running the following code either in **_CreatePlugin_** or in **_OnProjectOpen_** event no form will be created/opened. In the described case **_OpenForm_** function returns "null".
```
var form = this.Viewer.UI.OpenForm(typeof(ReceiverForm), this.MessageBus);
```
When opening another project after Walkinside has been successfully opened anything works fine.

The reason to do so is to open a specific plugin on startup without any user interaction.
Are there any other events to consider? Any ideas?

**Comment by andgonro** [comment]
Hello @kkneip,
@kveretennicov will come with a more detailed explanation if there is a way to open a form on project loading. The problem you are facing is that the layout loading is done after the form is loaded and your form gets closed to meet the layout.
The way to achieve what you want at this point is to open manually your form and then save the layout; Windowing|Layout|save|default. From this moment your form will be opened as soon as the project is loaded.
You will need to do this for all the projects as the layout is stored per project

**Comment by kveretennicov** [comment]
Sorry, it took longer than I expected to get to this issue. I had a bit of time last week to look into it, although not enough for detailed analysis.

I could confirm that `OpenForm` neither fails nor opens the form when called from `CreatePlugin` handler. I was able to work around that by attaching a handler to `Application.Idle`, so that `OpenForm` call is postponed:

```c#
CreatePlugin(IVRViewerSdk viewer)
{
    ...
    this.m_viewer = viewer;
    Application.Idle += this.OpenFormOnce; 
}

void OpenFormOnce(object sender, EventArgs args)
{
    Application.Idle -= this.OpenFormOnce;
    this.m_viewer.UI.OpenForm(...);
}
```

Can you try if it works for you?
Alternatively, try saving layout like @andgonro suggested. It won't be a code-level solution, but will do the trick still.

**Comment by kkneip** [comment]
Hi @kveretennicov,

your proposed workaround worked for me. Thanks a lot!
