### ISSUE TITLE
Open Keymap from the SDK

### ISSUE THREAD

**Issue by andgonro** [walkinside/sdk#28]
Hi,

I would like to be able to open the Keymap window for my vrp files but I don't find any way to do so through the SDK, can you help?

**Comment by kveretennicov** [comment]
The API does not provide plug-ins with any supported way to open Walkinside Viewer's standard Keymap window. Same for other Viewer windows, like CAD Hierarchy or Viewpoints. This is because we feel that the end user should stay in control of Walkinside environment.

To make sure that Keymap is always opened when the project is opened, you can prepare a layout for the project. Please see [Walkinside documentation on Layout](https://support.industry.siemens.com/cs/mdm/109737578?c=61679079307&lc=en-AE).

If you need to show and hide Keymap based on some logic in your plug-in, we'd like to hear more about what you are trying to build.

CC @walkinside/devs

**Comment by kveretennicov** [comment]
Closing for now due to inactivity.
