### ISSUE TITLE
Retrieve all attribute names

### ISSUE THREAD

**Issue by andgonro** [walkinside/sdk#4]
As a SDL developer
I want to be able to retrieve the names of all the attributes available in my project
so I can propose a drop-down menu with them when the user needs to select an attribute

Ex. FRT Generator requires to enter attribute names but this may have a typo as the user needs to enter the name manually. Ideally the user should just select from the available drop down menu

**Comment by kveretennicov** [comment]
@andgonro, indeed, with current API the only way is to iterate over all attribute sources of the project, then iterate over all attribute instances and then filter for distinct keys. Something like

```c#
var allKeys = project.AttributeSources.GetAll()
                     .SelectMany(s => s.GetAll().Select(a => a.Key))
                     .Distinct();
```

This can take too long for bigger projects, of course.

For your case, do you need to get all keys from the `IProject` or from the specific `IAttributeSource` (PDS, PDMS, etc.)? We have an unimplemented `IProject.GetKnownAttributeKeys()`, but I suspect it may be less useful (and slower) for you than `IAttributeSource.GetAllKeys`. That's because `IProject.GetKnownAttributeKeys()` would include Walkinside attributes, not only CAD attributes.

CC @walkinside/devs

**Comment by andgonro** [comment]
@kveretennicov I should be able to retrieve all the attributes from different data sources available but not the Walkinside attributes, indeed.

**Comment by griemens** [comment]
Is the following not what you need ?
ICollection<IVRAttributeKey> names = SDKViewer.ProjectManager.DatabaseManager.GetAllAttributes();
Now you can use linq or for each to get all the names out of the collection.
foreach(var key in names)
   key.PrettyName <- use this in youor drop down.

**Comment by kveretennicov** [comment]
@griemens, true, that would work for Viewer SDK, but @andongro's request is about Data SDK.

**Comment by griemens** [comment]
Oops true. My mistake.

**Comment by gcorvala** [comment]
Dear @andgonro, feel free to reopen if you feel that the workaround is not fitting your needs. Regards.
