### ISSUE TITLE
API obsolete???

### ISSUE THREAD

**Issue by dkOogway** [walkinside/sdk#53]
Hi,
Which API is obsolete?
```
//SDKViewer.UI.ContextMenu3D 
//or 
//VR3DControl.ContextMenuStrip
```
In document says both are obsolete. Please tell me which one is to use or any other API could be used instead of these API's?

![image](https://user-images.githubusercontent.com/39617362/46011224-81964780-c0c5-11e8-8b59-ca612cf89e5a.png)
--------------
![image](https://user-images.githubusercontent.com/39617362/46011312-c02c0200-c0c5-11e8-8490-2e5df8b142d7.png)

--
Thanks

**Comment by Agadoul** [comment]
Thanks for your feedback.
In 36xx,we introduced the notion of commands in order to abstract the ui from the sdk. you can still add entries in the context menu using the CommandManager.

You can have a look here :https://github.com/walkinside/sdk/blob/master/examples/official/Viewer%20SDK/Ex6.ContextMenu/MainForm.cs

Feel free to comment this approach.
Best regards.

**Comment by dkOogway** [comment]
Thank you Agadoul, to use above API. I need COMOS version 10.2.36.22.
Currently am using COMOS Walkinside 10.2.34.46 version. It does not have suggested API.

Anyway thanks for the information about new feature. :)

-- Kind Regards
