### ISSUE TITLE
Save and Load settings for my plugin

### ISSUE THREAD

**Issue by griemens** [walkinside/sdk#6]
What is an SDK method i can use to store and retreave values for my plugin.
For example would like to store the last used search query to the project so when the solution is opened again for this project it can pre fill the query value.

Currently found IVRSettings.SetString and IVRSettings.GetString but they are marked as obsolete in help file.

What would be recomended ?

**Comment by kveretennicov** [comment]
This is currently a gap in Viewer SDK API. We deprecated old methods in `IVRSettings` and `IVRSettingsManager`, because they were not so great as a foundation for future. They will normally stay around at least until Walkinside 10.3, and the only choice so far, but indeed an alternative API still has to be added.

For the "right now" I would recommend to use a unique prefix for all settings of your plug-in/application (a `System.Guid.NewGuid()` works well).

**Comment by Agadoul** [comment]
@kveretennicov the Guid should be constant per plugin. Using the Visual studio project guid might work. 
@kveretennicov how would you store this System.Guid.NewGuid() for it to be retrievable when the plugin is loaded again after Walkinside exited?

**Comment by kveretennicov** [comment]
As for the new plug-in Settings API I can think of the following. First, we're talking of per-project settings (leaving aside per-machine/per-user settings); basically, same service that `IVRSettingsManager` provided. Second, it would be useful to avoid that different plug-ins read/write each other's settings by accident; also to avoid setting name clashes. This can be achieved by careful coding on SDK users' side (e.g., namespacing with Guid-prefix), but a little help from the SDK can go a long way.

With that in mind, the API can look like this:

```c#
interface IVRPluginSettings
{
    T GetValue<T>(string name, T default);
    void SetValue<T>(string name, T value);
}

...

public bool CreatePlugin(IVRViewerSdk viewer)
{
    var settingsNamespace = "..."; // Something unique to this plug-in. 
    IVRPluginSettings settings = viewer.Settings.GetPluginSettings(settingsNamespace);
    // ... read/write settings as usual
}
```

In 10.2 we started to use new `IVRSetting` interface that provides more than basic `GetValue/SetValue`. That one can be used instead of simple getter/setter methods of `IVRPluginSettings`.

Regarding the setting value types, I believe we should support reading/writing any JSON-serializable type. This helps with array-valued or struct-valued settings, which is a bit more awkward to achieve otherwise. Of course, nothing prevents plug-ins from using string settings with manual JSON serialization/deserialization, but it's again something SDK can help with.

**Comment by kveretennicov** [comment]
This is how the current draft looks:

```c#
IVRViewerSdk viewer = ...;
var myPluginNamespace = new Guid("..."); // Use some value generated in advance.
var settings = viewer.ForPreview.GetProjectSettings(myPluginNamespace);
var mySetting = settings.GetSetting("my setting", defaultValue: "...");
var myOtherSetting = settings.GetSetting("setting 2", defaultValue: 0);
...
viewer.UI.ShowInfo(mySetting.Value);
...
mySetting.Value = "new value";
```

There also a `ValueChanged` event on the setting:

```c#
mySetting.ValueChanged += (sender, args)
{
    ...
};
```

**Comment by kveretennicov** [comment]
This will be available for preview in the next pre-release package (10.2.33.44.0). Please try it out and leave your feedback here in GitHub. When we have enough usage reports from SDK users, we will be able to promote it to official support.

For the time being I close this issue. 
Thank you.
