### ISSUE TITLE
Request for a database example (Exporter / Viewer)

### ISSUE THREAD

**Issue by griemens** [walkinside/sdk#8]
Hi,

Would like to store database attributes to my Walkinside project using the Exporter SDK API, and have them accessible int Walkinside Viewer with IVRDatabaseManager.
As I can understand from SDK documentation on the viewer side I need to implement a plugin and develop a database class which implements IVRDatabase interface and register it to IVRDatabaseManager.RegisterDatabase.

Is there an API that can support my case on the exporter SDK ?

Thanks.

**Comment by kveretennicov** [comment]
I'm afraid the story with implementing custom attribute data stores using SDK is not well-supported across the board.

Exporter SDK API is in "preview" and at the moment too difficult to use without knowing its implementation. It will require some work for us to be able to support it at the level close to Viewer SDK API.

Even on the Viewer SDK side, although `IVRDatabase` and `IVRDatabaseManager.RegisterDatabase` exist, they don't help to cover online mode, when project data is in Walkinside Server.

So I would say that SDK at the moment does not really support your case. We plan to address this by introducing a generic attribute data store, which can be populated using Data SDK. It should be accessible to Viewer SDK plug-ins and most likely have some `IVRDatabase` implementation too.

Any details you can share about where you would implement such custom attributes are welcome.

CC @walkinside/devs @walkinside/staff

**Comment by griemens** [comment]
Thanks for the clarification.

Would like to use the SDK to build walkinside models from IFC files (and maybe STEP).
IFC is a common format in the BIM world. 
http://www.buildingsmart-tech.org/specifications/ifc-overview
http://www.openbim.org/

But to be able to use Walkinside models for BIM workflows, access to the attributes in IFC files is important.

Will focus for time being on 3D information only and when is finished maybe the new versions of the SDK will support the attributes also for online models.

Kind regards.

**Comment by kveretennicov** [comment]
It looks like we will not be able to help you with this request.

Exporter SDK API has been in "preview" mode since around 2015, but never got wider traction among SDK developers. This is partly due to lack of documentation and design, but also due to being somewhat niche.

As there are no plans to improve this API towards "official" level of support and seeing how its relevance decreases thanks to new Builders added to standard Walkinside, it has been decided to officially discontinue Exporter SDK API in upcoming release

If you need to get attributes into Walkinside project, it should be done using Walkinside Builder for one of the supported CAD formats, like JT, PDMS or others.

**Comment by griemens** [comment]
ok, thanks for the information.
